@rem This batch will out put svn revision to revision.txt.
@rem SVN_REVISION will be set from build system.
@rem SRDM_VERSION will be set from build system.
@rem If you run this batch in command prompt, iPAUSVNRevision.java will be updated with SVN Version & SRDM version".
@rem This batch will out put svn revision to revision.txt.
@rem SVN_REVISION will be set from build system.
@rem SRDM_VERSION will be set from build system.
@rem If you run this batch in command prompt, iPAUSVNRevision.java will be updated with SVN Version & SRDM version".
@echo off
set SVN_REV_OUT_PATH=ClientProjects\webuilibrary\src\srdm\cloud\client\common
set SVN_REV_OUT_FSS_PATH=ClientProjects\fssuilibrary\src\srdm\cloud\client\common
set SVN_REV_OUT_SECDB_PATH=ClientProjects\secdbuilibrary\src\srdm\cloud\client\common
@REM set SVN_REV_OUT_FD_PATH=ClientProjects\fduilibrary\src\srdm\cloud\client\common
set SVN_REV_OUT_AM_PATH=ClientProjects\amuilibrary\src\srdm\cloud\client\common

@rem For Browser Cache issue, Paths are added to version Images & css files.
set WEBUI_PATH=ClientProjects\WebUI\war
set SECDB_PATH=ClientProjects\SecDB\war
set FSS_PATH=ClientProjects\FSS\war
@REM set FD_PATH=ClientProjects\fd\war
set AM_PATH=ClientProjects\am\war

set TMP_REVISION=0000
set SRDM_VERSION=0.0.0

@rem if defined SVN_REVISION_1 (
@rem 	if %TMP_REVISION% LSS %SVN_REVISION_1% set TMP_REVISION=%SVN_REVISION_1%
@rem )
@rem if defined SVN_REVISION_2 (
@rem 	if %TMP_REVISION% LSS %SVN_REVISION_2% set TMP_REVISION=%SVN_REVISION_2%
@rem )
@rem if defined SVN_REVISION_3 (
@rem 	if %TMP_REVISION% LSS %SVN_REVISION_3% set TMP_REVISION=%SVN_REVISION_3%
@rem )
@rem if defined SVN_REVISION_4 (
@rem 	if %TMP_REVISION% LSS %SVN_REVISION_4% set TMP_REVISION=%SVN_REVISION_4%
@rem )
@rem if defined SVN_REVISION_5 (
@rem 	if %TMP_REVISION% LSS %SVN_REVISION_5% set TMP_REVISION=%SVN_REVISION_5%
@rem )

if defined SVN_REVISION (
	set TMP_REVISION=%SVN_REVISION%
)

if defined VERSION (
	set SRDM_VERSION=%VERSION%
)

set SRDM_VER_REV=%SRDM_VERSION%.%TMP_REVISION%

@rem For WebUI
echo //This file is automatically generated for SVN Version Number > %SVN_REV_OUT_PATH%\SVNRevision.java
echo package srdm.cloud.client.common; >> %SVN_REV_OUT_PATH%\SVNRevision.java
echo public class SVNRevision { >> %SVN_REV_OUT_PATH%\SVNRevision.java
echo public static String SRDM_VERSION = "%SRDM_VER_REV%"; >> %SVN_REV_OUT_PATH%\SVNRevision.java
echo } >> %SVN_REV_OUT_PATH%\SVNRevision.java

@rem For FSS
echo //This file is automatically generated for SVN Version Number > %SVN_REV_OUT_FSS_PATH%\SVNRevision.java
echo package srdm.cloud.client.common; >> %SVN_REV_OUT_FSS_PATH%\SVNRevision.java
echo public class SVNRevision { >> %SVN_REV_OUT_FSS_PATH%\SVNRevision.java
echo public static String SRDM_VERSION = "%SRDM_VER_REV%"; >> %SVN_REV_OUT_FSS_PATH%\SVNRevision.java
echo } >> %SVN_REV_OUT_FSS_PATH%\SVNRevision.java

@rem For SecDB
echo //This file is automatically generated for SVN Version Number > %SVN_REV_OUT_SECDB_PATH%\SVNRevision.java
echo package srdm.cloud.client.common; >> %SVN_REV_OUT_SECDB_PATH%\SVNRevision.java
echo public class SVNRevision { >> %SVN_REV_OUT_SECDB_PATH%\SVNRevision.java
echo public static String SRDM_VERSION = "%SRDM_VER_REV%"; >> %SVN_REV_OUT_SECDB_PATH%\SVNRevision.java
echo } >> %SVN_REV_OUT_SECDB_PATH%\SVNRevision.java

@rem For FD
@REM echo //This file is automatically generated for SVN Version Number > %SVN_REV_OUT_FD_PATH%\SVNRevision.java
@REM echo package srdm.cloud.client.common; >> %SVN_REV_OUT_FD_PATH%\SVNRevision.java
@REM echo public class SVNRevision { >> %SVN_REV_OUT_FD_PATH%\SVNRevision.java
@REM echo public static String SRDM_VERSION = "%SRDM_VER_REV%"; >> %SVN_REV_OUT_FD_PATH%\SVNRevision.java
@REM echo } >> %SVN_REV_OUT_FD_PATH%\SVNRevision.java

@rem For AM
echo //This file is automatically generated for SVN Version Number > %SVN_REV_OUT_AM_PATH%\SVNRevision.java
echo package srdm.cloud.client.common; >> %SVN_REV_OUT_AM_PATH%\SVNRevision.java
echo public class SVNRevision { >> %SVN_REV_OUT_AM_PATH%\SVNRevision.java
echo public static String SRDM_VERSION = "%SRDM_VER_REV%"; >> %SVN_REV_OUT_AM_PATH%\SVNRevision.java
echo } >> %SVN_REV_OUT_AM_PATH%\SVNRevision.java

mkdir %WEBUI_PATH%\%SRDM_VER_REV%
move /Y %WEBUI_PATH%\0.0.0.0000\images %WEBUI_PATH%\%SRDM_VER_REV%
move /Y %WEBUI_PATH%\0.0.0.0000\WebUI.css %WEBUI_PATH%\%SRDM_VER_REV%

mkdir %SECDB_PATH%\%SRDM_VER_REV%
move /Y %SECDB_PATH%\0.0.0.0000\images %SECDB_PATH%\%SRDM_VER_REV%
move /Y  %SECDB_PATH%\0.0.0.0000\SecDB.css %SECDB_PATH%\%SRDM_VER_REV%

mkdir %FSS_PATH%\%SRDM_VER_REV%
move /Y  %FSS_PATH%\0.0.0.0000\images %FSS_PATH%\%SRDM_VER_REV%
move /Y %FSS_PATH%\0.0.0.0000\FSS.css %FSS_PATH%\%SRDM_VER_REV%

@REM mkdir %FD_PATH%\%SRDM_VER_REV%
@REM move /Y %FD_PATH%\0.0.0.0000\images %FD_PATH%\%SRDM_VER_REV%
@REM move /Y %FD_PATH%\0.0.0.0000\fd.css %FD_PATH%\%SRDM_VER_REV%

mkdir %AM_PATH%\%SRDM_VER_REV%
move /Y %AM_PATH%\0.0.0.0000\images %AM_PATH%\%SRDM_VER_REV%
move /Y %AM_PATH%\0.0.0.0000\am.css %AM_PATH%\%SRDM_VER_REV%